[package]
name = "eml"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version= "1.1.2", features= ["v4", "fast-rng", "macro-diagnostics"] }
nom = "7.1.1"
clap = { version = "3.2.20", features = ["derive"] }

indoc = "1.0.0" # temp

[dev-dependencies]
indoc = "1.0.0"
